apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deploy-autoscaling
  labels:
    app : my-k8s-mywebsit
    owner: AntonGainullin
spec:
  replicas: 2
  selector:
    matchLabels:
      project: mywebsaut
  template:
    metadata:
      labels:
        project: mywebsaut
    spec:
      containers:
        - name : myweb1aut
          image: antongaynullin/mywebsit:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-pod-service
  labels:
    env  : prod
    owner: AntonGainullin
spec:
  selector:
    project: mywebsaut  # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8080  # Port on Load Balancer
      targetPort: 8080  # Port on POD
  type: NodePort
